// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"time"
)

type ApiToken struct {
	ID         int64      `json:"id"`
	Name       string     `json:"name"`
	TokenHash  string     `json:"token_hash"`
	CreatedAt  time.Time  `json:"created_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
}

type App struct {
	ID        int64     `json:"id"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
}

type AppPlatform struct {
	ID            int64     `json:"id"`
	AppID         int64     `json:"app_id"`
	Platform      string    `json:"platform"`
	PackageName   string    `json:"package_name"`
	PlayEnabled   int64     `json:"play_enabled"`
	SignKeystore  string    `json:"sign_keystore"`
	SignConfig    string    `json:"sign_config"`
	SignSha256    string    `json:"sign_sha256"`
	CreatedAt     time.Time `json:"created_at"`
	PlayAccountID *int64    `json:"play_account_id"`
	PruneKeep     *int64    `json:"prune_keep"`
}

type Config struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type PlayAccount struct {
	ID          int64     `json:"id"`
	Label       string    `json:"label"`
	Credentials string    `json:"credentials"`
	CreatedAt   time.Time `json:"created_at"`
}

type Release struct {
	ID            int64     `json:"id"`
	AppPlatformID int64     `json:"app_platform_id"`
	VersionCode   int64     `json:"version_code"`
	VersionName   string    `json:"version_name"`
	Channel       string    `json:"channel"`
	Notes         string    `json:"notes"`
	Sha256        string    `json:"sha256"`
	SizeBytes     int64     `json:"size_bytes"`
	FileName      string    `json:"file_name"`
	CreatedAt     time.Time `json:"created_at"`
	PlayStatus    string    `json:"play_status"`
	PlayError     string    `json:"play_error"`
	PlayRelease   string    `json:"play_release"`
}

type Session struct {
	TokenHash string    `json:"token_hash"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
