// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playconfig.sql

package dbgen

import (
	"context"
)

const listPlatformsWithPlay = `-- name: ListPlatformsWithPlay :many
SELECT ap.id, ap.app_id, ap.platform, ap.package_name, ap.play_enabled, ap.play_credentials, ap.sign_keystore, ap.sign_config, ap.sign_sha256, ap.created_at FROM app_platforms ap WHERE ap.play_enabled = 1
`

func (q *Queries) ListPlatformsWithPlay(ctx context.Context) ([]AppPlatform, error) {
	rows, err := q.db.QueryContext(ctx, listPlatformsWithPlay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPlatform{}
	for rows.Next() {
		var i AppPlatform
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Platform,
			&i.PackageName,
			&i.PlayEnabled,
			&i.PlayCredentials,
			&i.SignKeystore,
			&i.SignConfig,
			&i.SignSha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlayConfig = `-- name: SetPlayConfig :exec
UPDATE app_platforms SET play_enabled = ?, play_credentials = ? WHERE id = ?
`

type SetPlayConfigParams struct {
	PlayEnabled     int64  `json:"play_enabled"`
	PlayCredentials string `json:"play_credentials"`
	ID              int64  `json:"id"`
}

func (q *Queries) SetPlayConfig(ctx context.Context, arg SetPlayConfigParams) error {
	_, err := q.db.ExecContext(ctx, setPlayConfig, arg.PlayEnabled, arg.PlayCredentials, arg.ID)
	return err
}
