// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playconfig.sql

package dbgen

import (
	"context"
)

const listAppsWithPlay = `-- name: ListAppsWithPlay :many
SELECT id, slug, package_name, platform, created_at, play_enabled, play_credentials, sign_keystore, sign_config, sign_sha256 FROM apps WHERE play_enabled = 1
`

func (q *Queries) ListAppsWithPlay(ctx context.Context) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listAppsWithPlay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.PackageName,
			&i.Platform,
			&i.CreatedAt,
			&i.PlayEnabled,
			&i.PlayCredentials,
			&i.SignKeystore,
			&i.SignConfig,
			&i.SignSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlayConfig = `-- name: SetPlayConfig :exec
UPDATE apps SET play_enabled = ?, play_credentials = ? WHERE id = ?
`

type SetPlayConfigParams struct {
	PlayEnabled     int64  `json:"play_enabled"`
	PlayCredentials string `json:"play_credentials"`
	ID              int64  `json:"id"`
}

func (q *Queries) SetPlayConfig(ctx context.Context, arg SetPlayConfigParams) error {
	_, err := q.db.ExecContext(ctx, setPlayConfig, arg.PlayEnabled, arg.PlayCredentials, arg.ID)
	return err
}
