// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: releasehub.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const apiTokenByHash = `-- name: ApiTokenByHash :one
SELECT id, name, token_hash, created_at, last_used_at FROM api_tokens WHERE token_hash = ?
`

func (q *Queries) ApiTokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, apiTokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const appBySlug = `-- name: AppBySlug :one
SELECT id, slug, package_name, platform, created_at, play_enabled, play_credentials, sign_keystore, sign_config, sign_sha256 FROM apps WHERE slug = ?
`

func (q *Queries) AppBySlug(ctx context.Context, slug string) (App, error) {
	row := q.db.QueryRowContext(ctx, appBySlug, slug)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PackageName,
		&i.Platform,
		&i.CreatedAt,
		&i.PlayEnabled,
		&i.PlayCredentials,
		&i.SignKeystore,
		&i.SignConfig,
		&i.SignSha256,
	)
	return i, err
}

const createApiToken = `-- name: CreateApiToken :execresult

INSERT INTO api_tokens (name, token_hash) VALUES (?, ?)
`

type CreateApiTokenParams struct {
	Name      string `json:"name"`
	TokenHash string `json:"token_hash"`
}

// api tokens
func (q *Queries) CreateApiToken(ctx context.Context, arg CreateApiTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createApiToken, arg.Name, arg.TokenHash)
}

const createApp = `-- name: CreateApp :execresult

INSERT INTO apps (slug, package_name, platform) VALUES (?, ?, ?)
`

type CreateAppParams struct {
	Slug        string `json:"slug"`
	PackageName string `json:"package_name"`
	Platform    string `json:"platform"`
}

// apps
func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createApp, arg.Slug, arg.PackageName, arg.Platform)
}

const createRelease = `-- name: CreateRelease :execresult

INSERT INTO releases (app_id, version_code, version_name, channel, notes, sha256, size_bytes, file_name)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateReleaseParams struct {
	AppID       int64  `json:"app_id"`
	VersionCode int64  `json:"version_code"`
	VersionName string `json:"version_name"`
	Channel     string `json:"channel"`
	Notes       string `json:"notes"`
	Sha256      string `json:"sha256"`
	SizeBytes   int64  `json:"size_bytes"`
	FileName    string `json:"file_name"`
}

// releases
func (q *Queries) CreateRelease(ctx context.Context, arg CreateReleaseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRelease,
		arg.AppID,
		arg.VersionCode,
		arg.VersionName,
		arg.Channel,
		arg.Notes,
		arg.Sha256,
		arg.SizeBytes,
		arg.FileName,
	)
}

const createSession = `-- name: CreateSession :exec

INSERT INTO sessions (token_hash, created_at, expires_at) VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	TokenHash string    `json:"token_hash"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

// sessions
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.TokenHash, arg.CreatedAt, arg.ExpiresAt)
	return err
}

const deleteApiToken = `-- name: DeleteApiToken :exec
DELETE FROM api_tokens WHERE id = ?
`

func (q *Queries) DeleteApiToken(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteApiToken, id)
	return err
}

const deleteApp = `-- name: DeleteApp :exec
DELETE FROM apps WHERE slug = ?
`

func (q *Queries) DeleteApp(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, deleteApp, slug)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteRelease = `-- name: DeleteRelease :exec
DELETE FROM releases WHERE app_id = ? AND version_code = ?
`

type DeleteReleaseParams struct {
	AppID       int64 `json:"app_id"`
	VersionCode int64 `json:"version_code"`
}

func (q *Queries) DeleteRelease(ctx context.Context, arg DeleteReleaseParams) error {
	_, err := q.db.ExecContext(ctx, deleteRelease, arg.AppID, arg.VersionCode)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const getConfig = `-- name: GetConfig :one

SELECT value FROM config WHERE key = ?
`

// config
func (q *Queries) GetConfig(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getConfig, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const latestReleaseForChannel = `-- name: LatestReleaseForChannel :many
SELECT id, app_id, version_code, version_name, channel, notes, sha256, size_bytes, file_name, created_at FROM releases
WHERE app_id = ? AND channel = ?
ORDER BY version_code DESC LIMIT 1
`

type LatestReleaseForChannelParams struct {
	AppID   int64  `json:"app_id"`
	Channel string `json:"channel"`
}

func (q *Queries) LatestReleaseForChannel(ctx context.Context, arg LatestReleaseForChannelParams) ([]Release, error) {
	rows, err := q.db.QueryContext(ctx, latestReleaseForChannel, arg.AppID, arg.Channel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Release{}
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.VersionCode,
			&i.VersionName,
			&i.Channel,
			&i.Notes,
			&i.Sha256,
			&i.SizeBytes,
			&i.FileName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiTokens = `-- name: ListApiTokens :many
SELECT id, name, token_hash, created_at, last_used_at FROM api_tokens ORDER BY created_at
`

func (q *Queries) ListApiTokens(ctx context.Context) ([]ApiToken, error) {
	rows, err := q.db.QueryContext(ctx, listApiTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApps = `-- name: ListApps :many
SELECT id, slug, package_name, platform, created_at, play_enabled, play_credentials, sign_keystore, sign_config, sign_sha256 FROM apps ORDER BY slug
`

func (q *Queries) ListApps(ctx context.Context) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.PackageName,
			&i.Platform,
			&i.CreatedAt,
			&i.PlayEnabled,
			&i.PlayCredentials,
			&i.SignKeystore,
			&i.SignConfig,
			&i.SignSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleases = `-- name: ListReleases :many
SELECT id, app_id, version_code, version_name, channel, notes, sha256, size_bytes, file_name, created_at FROM releases WHERE app_id = ? ORDER BY version_code DESC
`

func (q *Queries) ListReleases(ctx context.Context, appID int64) ([]Release, error) {
	rows, err := q.db.QueryContext(ctx, listReleases, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Release{}
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.VersionCode,
			&i.VersionName,
			&i.Channel,
			&i.Notes,
			&i.Sha256,
			&i.SizeBytes,
			&i.FileName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxVersionCode = `-- name: MaxVersionCode :one
SELECT COALESCE(MAX(version_code), 0) AS max_code FROM releases WHERE app_id = ?
`

func (q *Queries) MaxVersionCode(ctx context.Context, appID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxVersionCode, appID)
	var max_code interface{}
	err := row.Scan(&max_code)
	return max_code, err
}

const releaseByAppAndCode = `-- name: ReleaseByAppAndCode :one
SELECT id, app_id, version_code, version_name, channel, notes, sha256, size_bytes, file_name, created_at FROM releases WHERE app_id = ? AND version_code = ?
`

type ReleaseByAppAndCodeParams struct {
	AppID       int64 `json:"app_id"`
	VersionCode int64 `json:"version_code"`
}

func (q *Queries) ReleaseByAppAndCode(ctx context.Context, arg ReleaseByAppAndCodeParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, releaseByAppAndCode, arg.AppID, arg.VersionCode)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.VersionCode,
		&i.VersionName,
		&i.Channel,
		&i.Notes,
		&i.Sha256,
		&i.SizeBytes,
		&i.FileName,
		&i.CreatedAt,
	)
	return i, err
}

const sessionByHash = `-- name: SessionByHash :one
SELECT token_hash, created_at, expires_at FROM sessions WHERE token_hash = ?
`

func (q *Queries) SessionByHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, sessionByHash, tokenHash)
	var i Session
	err := row.Scan(&i.TokenHash, &i.CreatedAt, &i.ExpiresAt)
	return i, err
}

const setConfig = `-- name: SetConfig :exec
INSERT INTO config (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetConfigParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetConfig(ctx context.Context, arg SetConfigParams) error {
	_, err := q.db.ExecContext(ctx, setConfig, arg.Key, arg.Value)
	return err
}

const touchApiToken = `-- name: TouchApiToken :exec
UPDATE api_tokens SET last_used_at = ? WHERE token_hash = ?
`

type TouchApiTokenParams struct {
	LastUsedAt *time.Time `json:"last_used_at"`
	TokenHash  string     `json:"token_hash"`
}

func (q *Queries) TouchApiToken(ctx context.Context, arg TouchApiTokenParams) error {
	_, err := q.db.ExecContext(ctx, touchApiToken, arg.LastUsedAt, arg.TokenHash)
	return err
}
