// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: signing.sql

package dbgen

import (
	"context"
)

const setSigningConfig = `-- name: SetSigningConfig :exec
UPDATE app_platforms SET sign_keystore = ?, sign_config = ?, sign_sha256 = ? WHERE id = ?
`

type SetSigningConfigParams struct {
	SignKeystore string `json:"sign_keystore"`
	SignConfig   string `json:"sign_config"`
	SignSha256   string `json:"sign_sha256"`
	ID           int64  `json:"id"`
}

func (q *Queries) SetSigningConfig(ctx context.Context, arg SetSigningConfigParams) error {
	_, err := q.db.ExecContext(ctx, setSigningConfig,
		arg.SignKeystore,
		arg.SignConfig,
		arg.SignSha256,
		arg.ID,
	)
	return err
}
